[.text-center]
=== _Beenear_
[frame=none]
[grid=none]
|===
^|Summary ^|Technical Environment

^.^|
_Position_: Lead Developer (*.NET*/Angular)

_Company_: Beenear SRL (*Var* Group)

_Industry_: *Software Services* 

_Location_: Iasi, Romania

_Contract Duration_: 12 months

^.^|
_Platforms_: *Windows* 11, Azure Cloud

_Frameworks_: *.NET* 6, Angular 13

_Languages_: *C#* 10, TypeScript 4.6

_Libraries_: *Resharper*, Moq, Mojo Portal, Autofac

_Tools_: Git, VS 2022, DataGrip, WebStorm, *Azure DevOps*
|===

[frame=none]
[grid=none]
|===
^|Product Description ^|Project Responsabilities

^.^|
OpenFinance is the leading and one of Italy's most *popular accounting* tools.

EasyOne is an *industry-leading CRM* used by thousands of customers across the Iberian peninsula.

^.^|
Responsible for *migrating* the legacy accounting software OpenGate from Microsoft WebForms to Angular 12. +

In charge of maintaining EasyOneCrm, a WPF application, along with the task of refactoring it to *microservices*.

|===

[%header]
[frame=none]
[grid=none]
|===
^| Key Achievements

^.^|
Increased the performance of OpenGate *threefold* by rewriting two critical components in Angular

*Mentored* one middle developer, three juniors, and one intern

Reduced loading time by *7x* by re-architecture-ing the Login process
|===