[.text-center]
== Accounting & CRM Team Lead @ Beenear (Romania)

[frame = none, grid = none, stripes = all]
|===
| |

^a|

[.big.underline]#*Technical Environment*#
[frame = none, grid = none, cols = "^.^a"]
!===

! *Languages*: C#, TypeScript

! *Frameworks*: .NET, Angular, mojoPortal

! *Tools*: Visual Studio, SQL Server, DataGrip, WebStorm, Autofac, Moq

!===

[.big.underline]#*Product Description*#
[frame = none, grid = none, cols = "^.^a"]
!===

! *Business*: _OpenFinance_ is Italy's leading accounting software, empowering businesses to streamline financial operations & make informed decisions. _EasyOne_ is an industry-leading CRM solution widely used across the Iberian peninsula, enabling businesses to build stronger customer relationships.

! *Technical*:  OpenFinance leverages a modern frameworks to deliver a responsive, scalable, and secure accounting platform. EasyOne is built on a solid GUI core and has been strategically refactored into a microservices architecture, enhancing its flexibility & maintainability

!===

^a|

[.big.underline]#*Key Achievements*#
[frame = none, grid = none, cols = "^.^a"]
!===

! Led the *successful migration* of the legacy OpenGate accounting software from Microsoft WebForms to Angular 12, modernizing the technology stack and significantly improving performance.

! Spearheaded the *refactoring* of EasyOneCrm, a monolithic WPF application, into a microservices architecture, enhancing scalability, flexibility, and maintainability.

! Increased OpenGate's performance *threefold* by rewriting two critical components in Angular, resulting in a significantly faster and more responsive user experience.

! *Mentored and guided* a team of five developers, including one middle developer, three juniors, and one intern, fostering their growth and development.

! Reduced login *loading time by 7x* through innovative re-architecting, dramatically improving user access and satisfaction.

!===

|===