[.text-center]
== _Experience & Training_

[frame = none, grid = none, stripes = all]
|===
| |

^.^a| 

[.big.underline]#*Crypto*#
[frame = none, grid = none, cols = "^.^a"]
!===

! Quant Developer with _.NET, Python & AWS_ @ *_Lykke_*
! Exchange Engineer with _.NET, React & GCP_ @ *_Klips_*

!===

[.big.underline]#*Financial*#
[frame = none, grid = none, cols = "^.^a"]
!===

! Banking Programmer with _VB, .NET, & Azure_ @ *_ING_*
! Payments Engineer with _.NET, Blazor & Azure_ @ *_Amex_*
! Derivatives Developer with _.NET, Angular & Azure_ @ *_Axa_*
! Liquidity Analyst with _PS, .NET & SQL_ @ *_SocGen_*

!===

[.big.underline]#*Energy*#
[frame = none, grid = none, cols = "^.^a"]
!=== 

! Renewables Developer with _.NET, PS & Azure_ @ *_SSE_*
! LPG Engineer with _.NET, Bicep & Azure_ @ *_Flogas_*
! Distribution Coder with _C++, .NET & Python_ @ *_Enedis_*

!===

[.big.underline]#*Other*#
[frame = none, grid = none, cols = "^.^a"]
!===

! Automation Coder with _.NET, Angular & Azure_ @ *_Tricentis_*
! Hardware Virtualization _Tech Lead_  @ *_Global Logic_*
! Accounting & CRM _Team Lead_ @ *_Beenear_*

!===

^.a|

[.big.underline]#*Courses*#
[frame = none, grid = none, cols = "^.^a"]
!===

! _Architecture & Design_ Class @ *Uncle Bob*
! _Advanced TDD & Refactoring_ Class @ *Uncle Bob*
! _Clean Code & TDD_ Class @ *Uncle Bob*

!===

[.big.underline]#*Education*#
[frame = none, grid = none, cols = "^.^a"]
!===

! *Business* Ecosystem Partner @ Baza7
! Bachelor of *Computer Science* @ UAIC
! *French Baccalaureate* Diploma @ CNME

!===

[.big.underline]#*Certifications*#
[frame = none, grid = none, cols = "^.^a"]
!===

! Expert *C#* Developer @ _Microsoft_
! Certified *Frontend* Developer @ W3Schools
! Professional *Scrum* Developer @ Agile Alliance
! Professional *Redis* Developer @ Redis Labs

!===

[.big.underline]#*Favorite Books*#
[frame = none, grid = none, cols = "^.^a"]
!===

! *C#* in Depth, *Extreme* Programming Explained, *Clean* Code & Architecture, *Refactoring*, Domain Driven *Design*, Design Patterns, The *Pragmatic* Programmer, *Soft* Skills

!===

|===