[.text-center]
=== _Société Générale_
[frame=none]
[grid=none]
|===
^|Summary ^|Technical Environment

^.^|
_Position_: Full Stack Developer (*.NET*/Angular)

_Company_: Société Générale Corporate & *Investment* Banking

_Industry_: *Banking*

_Location_: Tours Société Générale (*La Défense*, France)

_Contract Duration_: 12 months

^.^|
_Platforms_: Windows 7/10, *Windows Server* 2016

_Frameworks_: .NET 4.5, SQL Server Integration Services

_Languages_: C# 5.0, *PowerShell* 5.1, T-SQL

_Libraries_: NInject, NCrunch, ZeroMQ, *Specflow*

_Tools_: Git, Vs 2019 & Code, SSMS, *TeamCity*, XL Deploy
|===

[frame=none]
[grid=none]
|===
^|Product Description ^|Project Responsabilities

^.^|
Liqor is an internal *financial application* responsible for computing various _liquidity metrics_ and generating afferent _reports_ demanded by the BDF (_Bank of France_) and the BCE (_European Central Bank_).

^.^|
I was part of the team responsible for *monitoring* the *production* environment. Moreover, I worked on implementing *new liquidity metrics* (_Basel III_), and *rewriting SSIS scripts*.
|===

[frame=none]
[grid=none]
|===
^| Key Achievements

^.^|
Wrote a custom _XML parser_ that reduced *threefold* the time required to integrate a custom _data source_

*Rewrote and optimized* two critical _SSIS scripts_, improving performance by over *35%*

*Redesigned the CI pipeline* while _TeamCity 2008_ to _2018_, improving performance by almost *one order of magnitude*

_Designed and implemented_ the *CD pipeline* leading the minimal human input during the deployment process 

*Taught and mentored* my newcomers on coding practices, software development, and architectural processes
|===