[.text-center]
=== _Tricentis_
[frame=none]
[grid=none]
|===
^|Summary ^|Technical Environment

^.^|
_Position_: Full Stack Developer (.NET/*Angular*)

_Company_: Tricentis GmbH

_Industry_: Software as as Service (*SaaS*)

_Location_: Vienna International Center (*Vienna*, Austria)

_Contract Duration_: 12 months

^.^|
_Platforms_: Windows 10, *Azure*

_Frameworks_: .NET 4.7, *ASP .NET*, Angular 6

_Languages_: C# 7.2, *TypeScript* 2.9

_Libraries_: NUnit, Moq, Resharper, SQL Server, *MongoDB*

_Tools_: SVN, Visual Studio/Code, *Robo 3T* SQL Server
|===

[frame=none]
[grid=none]
|===
^|Product Description ^|Project Responsabilities

^.^|
Tricentis *Tosca* is a software solution that is geared towards *automating*  application *testing*.

^.^|
Breaking down the monolithic architecture into *microservices*. Migrating from SVN to *Git*. Building *CI & CD* pipelines.
|===


[frame=none]
[grid=none]
|===
^| Key Achievements

^.^|
Improved the overall application performance by *over 50%* thanks to the decommissioning of the service bus

Added two new *features* to the Cloud Portal 1) User & Project Management 2) User Profile Editor

Implemented *health check* mechanisms to the microservices to improve system resiliency

Increased the ease of use of the application by adding an essential application setting: configurable *Auth0 token* storage
|===